package android.app.job;
import android.content.Context;
public class JobScheduler {
 // Android SDK 36 values, present since API 34 (deadline is newer).
 public static final int PENDING_JOB_REASON_INVALID_JOB_ID=-2,PENDING_JOB_REASON_EXECUTING=-1,PENDING_JOB_REASON_UNDEFINED=0,PENDING_JOB_REASON_APP=1,PENDING_JOB_REASON_APP_STANDBY=2,PENDING_JOB_REASON_BACKGROUND_RESTRICTION=3,PENDING_JOB_REASON_CONSTRAINT_BATTERY_NOT_LOW=4,PENDING_JOB_REASON_CONSTRAINT_CHARGING=5,PENDING_JOB_REASON_CONSTRAINT_CONNECTIVITY=6,PENDING_JOB_REASON_CONSTRAINT_CONTENT_TRIGGER=7,PENDING_JOB_REASON_CONSTRAINT_DEVICE_IDLE=8,PENDING_JOB_REASON_CONSTRAINT_MINIMUM_LATENCY=9,PENDING_JOB_REASON_CONSTRAINT_PREFETCH=10,PENDING_JOB_REASON_CONSTRAINT_STORAGE_NOT_LOW=11,PENDING_JOB_REASON_DEVICE_STATE=12,PENDING_JOB_REASON_JOB_SCHEDULER_OPTIMIZATION=13,PENDING_JOB_REASON_QUOTA=14,PENDING_JOB_REASON_USER=15,PENDING_JOB_REASON_CONSTRAINT_DEADLINE=16;
 public JobInfo pending=new JobInfo();public int reason,jobReads,reasonReads,jobId,reasonJobId;public Throwable jobFailure,reasonFailure;
 public JobInfo getPendingJob(int id){jobReads++;jobId=id;Context.raise(jobFailure);return pending;}
 public int getPendingJobReason(int id){reasonReads++;reasonJobId=id;Context.raise(reasonFailure);return reason;}
}
